# Generated by Django 4.2.30 on 2026-08-01 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title describing the task', max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, default='', help_text='Optional detailed description')),
                ('completed', models.BooleanField(default=False, help_text='Whether the task has been completed')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, help_text='Task priority level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['completed'], name='tasks_task_complet_1ed563_idx'), models.Index(fields=['priority'], name='tasks_task_priorit_a900d4_idx'), models.Index(fields=['created_at'], name='tasks_task_created_be1ba2_idx')],
            },
        ),
    ]
